import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :my_card_game, MyCardGameWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "VERY_SECRET_DEV_KEY_BASE_CHANGE_ME", # Replace with a long random string
  watchers: [
    # Example for esbuild, not strictly needed for --no-html, but often present
    # node: [
    #  "node_modules/esbuild/bin/esbuild",
    #  "--bundle",
    #  "--target=es2017",
    #  "--outdir=../priv/static/assets",
    #  "--external:/fonts/*",
    #  "--external:/images/*",
    #  "js/app.js"
    # ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable LiveReload server
config :phoenix_live_reload,
  patterns: [
    ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
    ~r"priv/gettext/.*(po)$",
    ~r"lib/my_card_game_web/(controllers|live|components)/.*(ex|heex)$"
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable server-side rendering for Navigational routes
# during development.
config :phoenix_live_view,
  debug_heex_annotations: true,
  enable_expensive_runtime_checks: true
  # server_render_for_navigation: false # Deprecated or default now

# Define the PubSub server name (matches what's in config.exs)
config :my_card_game, pubsub_server: MyCardGame.PubSub
